### PR TITLE
feat: Add lobby

### PR DESCRIPTION
**Pull request by juddey**
This PR implements the beginning stages of a lobby, which is designed to be the first place that a user lands when they either log in or register for playdate.

A basic app model is added, plus an app instance model which is waiting area for people who are waiting to start an app.  The game instance model is backed by a GenServer, and reflects the ephermal nature of the `waiting-to-start-app` state.

App users are also added, to pass through to the game components when the use presses "Start App".

Relates to: #6 

Example Screenshot (unstyled as yet :)

image

### CODE REVIEW

**Comment by juddey** [comment]
@rellen I've tagged you as a reviewer but rather than review the entire 57 files I was just interested in your opinion about namespacing the battle-wordle game. In some senses battle wordle is a game and not an app so I wondered if you thought we should retain that nomenclature, I've already added some namespacing at the top level, but didn't want to apply that universally without discussion.

image

Anyway, appreciate your thoughts. Tomorrow @jimsynz and I can slug it out on the Rest of the PR :tm:

**Review by jimsynz — APPROVED** [review]
lots of typing

**Comment by jimsynz** [comment]
@juddey this PR will need rebasing.

**Comment by juddey** [comment]
Keeping this branch for the moment as theres a replica case for zach in aba933e

**Pull request merged**
